import "./globals.css";

import { Exo_2, Raleway } from "next/font/google";

import type { Metadata } from "next";
import { Providers } from "./providers";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const exo = Exo_2({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${raleway.variable} ${exo.variable} antialiased font-sans dark:bg-black`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
